### ISSUE TITLE
Выпадающий список

### ISSUE THREAD

**Issue by tiproktikum** [khusamov/dayplanner#2]
**Список должен быть таким:**

Удалить
ОКНОТЭК
ПСК
СТЕЛПЛАСТ
ECOHOUSE
ОКНА САННИ
ПЛАСТОКНО
МОСКОВСКАЯ ОКОННИЦА
ПАНОКНА
ДРУГОЕ

**Comment by khusamov** [comment]
Окнотэк
ПСК
Стелпласт
Ecohouse
Окна Санни
Пластокно
Московская Оконница
Панокна
Другое

**Comment by tiproktikum** [comment]
ПСК

**Comment by tiproktikum** [comment]
Окнотэка в списке нет
