### ISSUE TITLE
Обновление списка

### ISSUE THREAD

**Issue by tiproktikum** [khusamov/dayplanner#3]
Если фокус на вкладке с программой DP не установлен, то голубое выделение текущего часа (строки) "залипает", т.е. например выделена строка 10 часов, наступило 11 часов, а выделение так и осталось на 10, однако, если нажать мышкой на эту вкладку с программой, то обновление происходит и выделение меняется на 11. 

Это неудобно.

**Comment by khusamov** [comment]
Вроде обновление происходить должно ТОЛЬКО по F5 (то есть по обновлению страницы). Так просто не будет обновляться.

**Comment by tiproktikum** [comment]
> Вроде обновление происходить должно ТОЛЬКО по F5 (то есть по обновлению страницы). Так просто не будет обновляться.

сейчас обновляется если тыкнуть мышкой в любое место страницы DP

**Comment by khusamov** [comment]
Теперь будет обновляться автоматически каждый час (и не важно на фоне или в фокусе).
